# university_security_checklist.py
import streamlit as st
import pandas as pd
from datetime import datetime
import io

st.set_page_config(page_title="University Security Checklist", layout="wide")

st.title("University Security Checklist — Action Planner")
st.markdown("""
Use this tool to create a prioritized security checklist for campus networks, systems, and people.
Select items that apply, add owner/priority/notes, then export as CSV for meetings or audits.
""")

# Master checklist (category, item, recommended examples)
MASTER = [
    ("Governance & Policy", "Acceptable Use Policy (AUP)", "Draft & publish; annual review"),
    ("Governance & Policy", "Incident Response Plan + Tabletop Drills", "Run tabletop every 6 months"),
    ("Identity & Access", "Central IAM + RBAC", "Azure AD / FreeIPA / Keycloak"),
    ("Identity & Access", "Multi-Factor Authentication (MFA)", "Duo, Microsoft Authenticator"),
    ("Network Security", "Network segmentation (VLANs / micro-segmentation)", "Staff / Student / Guest / Research"),
    ("Network Security", "Next-Gen Firewall (NGFW)", "Palo Alto / Fortinet / pfSense"),
    ("Network Security", "Web Application Firewall (WAF)", "ModSecurity / Cloud WAF"),
    ("Endpoint", "EDR on endpoints", "CrowdStrike / SentinelOne / OSQuery"),
    ("Visibility", "Central logging & SIEM", "Splunk / ELK / LogRhythm"),
    ("Monitoring", "Network IDS/IPS", "Suricata / Snort"),
    ("Vulnerability", "Vuln scanning + patching automation", "Nessus / OpenVAS; WSUS/SCCM"),
    ("Data Protection", "DLP + Encryption + Backups", "Veeam / Native encryption"),
    ("Access Control", "NAC / 802.1X", "Cisco ISE / Aruba ClearPass"),
    ("Remote Access", "VPN or ZTNA", "OpenVPN / Palo Alto GlobalProtect"),
    ("Operations", "Configuration management & secure baselines", "Templates, Ansible"),
    ("People", "Security awareness training", "Phishing simulations"),
    ("Continuity", "Business continuity & disaster recovery", "Test restore quarterly"),
    ("Physical", "Secure network closets & OOB management", "Locked racks, serial console"),
    ("Monitoring", "Network TAPs / SPAN for forensics", "Visibility at egress"),
    ("Other", "Research data segregation and controls", "Isolate clusters, MFA"),
]

# Build UI
st.header("Select controls to include in your plan")
cols = st.columns([3,1,1,2])  # headings
cols[0].markdown("**Control (category - item)**")
cols[1].markdown("**Priority**")
cols[2].markdown("**Owner**")
cols[3].markdown("**Notes**")

rows = []
for idx, (cat, item, example) in enumerate(MASTER):
    row_col1, row_col2, row_col3, row_col4 = st.columns([3,1,1,2])
    key_base = f"r{idx}"
    include = row_col1.checkbox(f"{cat} — {item}  \n*{example}*", key=key_base + "_inc")
    if include:
        priority = row_col2.selectbox("Priority", ["Critical","High","Medium","Low"], key=key_base+"_prio")
        owner = row_col3.text_input("Owner (team/person)", key=key_base+"_owner")
        note = row_col4.text_area("Notes / deadline", key=key_base+"_note", height=60)
        rows.append({
            "category": cat,
            "item": item,
            "example": example,
            "priority": priority,
            "owner": owner,
            "notes": note,
            "selected_at": datetime.now().isoformat(timespec='seconds')
        })

st.markdown("---")

st.header("Selected items preview")
if rows:
    df = pd.DataFrame(rows)
    st.dataframe(df)
    # CSV download
    csv = df.to_csv(index=False).encode('utf-8')
    st.download_button(
        label="Export selected checklist to CSV",
        data=csv,
        file_name=f"university_security_checklist_{datetime.now().strftime('%Y%m%d_%H%M')}.csv",
        mime="text/csv"
    )

    # Simple generated action plan text
    st.markdown("#### Quick action plan (generated):")
    grouped = df.sort_values(["priority"]).groupby("priority")
    for prio, g in grouped:
        st.markdown(f"**{prio} priority ({len(g)} items)**")
        for _, r in g.iterrows():
            owner = r['owner'] or "TBD"
            note = r['notes'] or ""
            st.write(f"- {r['item']} (Owner: {owner}) {(' | ' + note) if note else ''}")
else:
    st.info("No items selected yet. Check boxes above to include controls in the plan.")

st.markdown("---")
st.write("Tip: start with Critical/High items for the first 90 days: IAM & MFA, patching, EDR, SIEM/Logging, NGFW, network segmentation, and backups.")

st.caption("Generated by university security checklist helper. Use this as a starting point — adapt to your scale and compliance needs.")
